export const ActionTypes = {
  SET_PRODUCT: "SET_PRODUCT",
  INCREMENT_COUNT: "INCREMENT_COUNT",
  DECREMENT_COUNT: "DECREMENT_COUNT",
  CHANGE_SELECTED_PRODUCT: "CHANGE_SELECTED_PRODUCT",
  ADD_TO_CART: "ADD_TO_CART"
};
